--- 
pool: 
  vmImage: ubuntu-16.04
steps: 
  - 
    displayName: "Copy Files to: $(build.artifactstagingdirectory)/Templates"
    inputs: 
      Contents: "*.json"
      SourceFolder: deployment
      TargetFolder: $(build.artifactstagingdirectory)/Templates
    task: CopyFiles@2
  - 
    displayName: "npm custom"
    inputs: 
      command: custom
      customCommand: "install --production"
      verbose: false
    task: Npm@1
  - 
    displayName: "Archive $(Build.SourcesDirectory)"
    inputs: 
      includeRootFolder: false
      rootFolderOrFile: $(Build.SourcesDirectory)
    task: ArchiveFiles@2
  - 
    displayName: "Publish Artifact: drop"
    task: PublishBuildArtifacts@1
trigger: 
  - master
